name: Hadoop Docker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          image=moby/buildkit:latest
        buildkitd-flags: --debug

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: askhadoop:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run container tests
      run: |
        docker run -d --name test-container \
          --memory=4g \
          --cpus=2 \
          askhadoop:test
        
        # Wait for container to be healthy
        timeout 300 bash -c 'while [[ "$(docker inspect -f {{.State.Health.Status}} test-container)" != "healthy" ]]; do sleep 5; done'
        
        # Run tests
        docker exec test-container bash -c '
          # Test SSH
          nc -zv localhost 22 || exit 1
          
          # Test HDFS
          nc -zv localhost 9870 || exit 1
          
          # Test YARN
          nc -zv localhost 8088 || exit 1
          
          # Test user permissions
          id hadoopuser || exit 1
          
          # Test Hadoop installation
          hadoop version || exit 1
          
          # Test Flume installation
          flume-ng version || exit 1
        '

  build-and-push:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          image=moby/buildkit:latest
        buildkitd-flags: --debug

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/askhadoop:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/askhadoop:3.3.6-ubuntu22.04
          ${{ secrets.DOCKERHUB_USERNAME }}/askhadoop:3.3.6-ubuntu22.04-${{ github.run_number }}
          ${{ secrets.DOCKERHUB_USERNAME }}/askhadoop:${{ github.ref_name }}-$(date +%Y%m%d)
        cache-from: type=gha
        cache-to: type=gha,mode=max 